function lesson(id, title, options) {
  return {
    id,
    title,
    durationMinutes: 10,
    ...options,
  };
}

const curriculumStages = [
  {
    id: 'grade-1-foundation',
    title: '一年级上: 拼音启蒙',
    description: '从声调、单韵母和基础声母开始，建立最核心的拼音读写能力。',
    lessons: [
      lesson('py-01', '声调与四线格', {
        tagline: '先认识拼音的“跑道”和“音高”。',
        focus: ['四线三格', '四个声调', '口型模仿'],
        goals: ['知道四线三格的基本位置', '能按顺序读出一声到四声', '能用手势区分音调高低'],
        teachingSteps: ['观察四线三格，知道字母应该住在中格和上格。', '跟读 a、á、ǎ、à，配合手势记住升降。', '用“妈、麻、马、骂”体验同一个音节不同声调的区别。'],
        practiceWords: ['mā 妈', 'má 麻', 'mǎ 马', 'mà 骂'],
        practiceSentence: '妈妈骑马。',
        miniTask: '边做手势边把四声读三遍。',
        checkpoints: ['能说出四线三格', '能辨认四个声调', '知道同一拼音加不同声调意思会变'],
      }),
      lesson('py-02', '单韵母 a o e', {
        tagline: '张大嘴、圆小嘴、嘴角平，感受元音口型。',
        focus: ['a', 'o', 'e'],
        goals: ['掌握 a、o、e 的口型', '能拼读带 a、o、e 的简单音节', '会在词语里听出这三个韵母'],
        teachingSteps: ['看镜子模仿 a、o、e 的口型变化。', '练读 ba、po、me、de 等两拼音节。', '从“爸爸、伯伯、鹅”中找出相应韵母。'],
        practiceWords: ['bā 爸', 'pō 坡', 'é 鹅', 'mó 模'],
        practiceSentence: '大白鹅在坡上。',
        miniTask: '找出家里两个含 a 或 o 音的词语。',
        checkpoints: ['能独立读 a o e', '能听出词语中的 a/o/e', '能拼出 ba、po、de'],
      }),
      lesson('py-03', '单韵母 i u ü 与 y w', {
        tagline: '学会尖嘴音和圆唇音，认识 y、w 的帮助作用。',
        focus: ['i', 'u', 'ü', 'yi', 'wu', 'yu'],
        goals: ['区分 i、u、ü 的口型', '会读 yi、wu、yu', '知道 y、w 在音节里的作用'],
        teachingSteps: ['练习 i、u、ü 的口型对比，特别是 ü 的撮口。', '认识 y、w 帮助 i、u、ü 单独成音节。', '练读 yi、wu、yu、ya、wa、ye。'],
        practiceWords: ['yī 衣', 'wū 屋', 'yú 鱼', 'yè 叶'],
        practiceSentence: '小鱼住在水屋里。',
        miniTask: '把 yi、wu、yu 连读两遍，再读 yǎ yè yóu。',
        checkpoints: ['能区分 i/u/ü', '知道 yi、wu、yu 不是两个音分开读', '会拼读 y 系和 w 系常见音节'],
      }),
      lesson('py-04', '声母 b p m f', {
        tagline: '感受送气和不送气的区别。',
        focus: ['b', 'p', 'm', 'f'],
        goals: ['能正确发出 b、p、m、f', '知道 b/p 的送气差别', '能拼读相关两拼音节'],
        teachingSteps: ['把手放在嘴前，感受 b 和 p 的气流不同。', '练读 ba、pa、ma、fa、bo、po、mo。', '用“爸爸、瀑布、妈妈、方法”找对应声母。'],
        practiceWords: ['bà 爸', 'pá 爬', 'mā 妈', 'fú 服'],
        practiceSentence: '妈妈扶爸爸爬坡。',
        miniTask: '对着纸条读 pa、po，看纸条有没有动起来。',
        checkpoints: ['能读准 b/p/m/f', '能区分 b 和 p', '能拼出 ba、po、ma、fu'],
      }),
      lesson('py-05', '声母 d t n l', {
        tagline: '舌尖轻轻碰上齿龈，练出口腔位置。',
        focus: ['d', 't', 'n', 'l'],
        goals: ['掌握 d、t、n、l 的发音部位', '区分 d/t 的送气', '会读相关常用词'],
        teachingSteps: ['观察舌尖位置，感受 d、t、n、l 的共同点。', '练读 da、ta、na、la、de、te、ni、lu。', '从“灯、兔、奶、路”中定位对应音节。'],
        practiceWords: ['dēng 灯', 'tù 兔', 'niú 牛', 'lù 路'],
        practiceSentence: '兔兔在大路边等你。',
        miniTask: '跟着节奏读 da-ta-na-la 三轮。',
        checkpoints: ['能说出 d/t 都在舌尖位置发音', '能拼读 ni、lu、da', '能区分 d 与 t'],
      }),
      lesson('py-06', '声母 g k h', {
        tagline: '后舌根发音，嘴巴打开一些更容易。',
        focus: ['g', 'k', 'h'],
        goals: ['会读 g、k、h', '会拼 ga、ke、huo 等音节', '知道 g/k 是不送气和送气的对应组'],
        teachingSteps: ['感受舌根抬起的位置，练 g、k、h。', '练习 ga、ka、ha、gu、ku、hu。', '从“哥哥、口、河”中找音节。'],
        practiceWords: ['gē 哥', 'kǒu 口', 'hé 河', 'gǔ 鼓'],
        practiceSentence: '哥哥在河口敲小鼓。',
        miniTask: '连续读 gu-ku-hu，保持声音清楚。',
        checkpoints: ['能读准 g/k/h', '会拼 gu、ke、hu', '知道 g 和 k 的气流差异'],
      }),
      lesson('py-07', '声母 j q x 与 ü 规则', {
        tagline: '掌握拼音里最常见的一条省写规则。',
        focus: ['j', 'q', 'x', 'ju', 'qu', 'xu'],
        goals: ['会读 j、q、x', '理解 j、q、x 后面的 u 实际读 ü', '能拼读 ju、que、xue'],
        teachingSteps: ['练习 j、q、x 的舌面前音。', '认识“见了 j q x，两点要省略”的规则。', '练读 ji、qi、xi、ju、qu、xu、xue。'],
        practiceWords: ['jī 鸡', 'qù 去', 'xuě 雪', 'jué 觉'],
        practiceSentence: '小鸡去雪地里学画。',
        miniTask: '把 ju、qu、xu 各读三遍，再说出它们原本带的是 ü。',
        checkpoints: ['能读准 j/q/x', '知道两点省略规则', '会拼 ju、qu、xue'],
      }),
      lesson('py-08', '声母 z c s', {
        tagline: '认识平舌音，让舌尖平平向前送气。',
        focus: ['z', 'c', 's'],
        goals: ['会读 z、c、s', '能分清 c 的送气和 z 的不送气', '会拼读 za、ce、si 等音节'],
        teachingSteps: ['练习平舌音，舌尖平伸不卷起。', '比较 za/ca、zu/cu、se/si 的不同。', '用“字、草、四”感受三个声母。'],
        practiceWords: ['zì 字', 'cǎo 草', 'sì 四', 'zǒu 走'],
        practiceSentence: '四只小兔走过草地。',
        miniTask: '把 z、c、s 和 zh、ch、sh 对比着试读一遍。',
        checkpoints: ['知道 zcs 是平舌音', '能读出 z 和 c 的差别', '会拼读 zi、ci、si'],
      }),
      lesson('py-09', '声母 zh ch sh r', {
        tagline: '卷舌音上场，舌尖向后卷起来。',
        focus: ['zh', 'ch', 'sh', 'r'],
        goals: ['掌握 zh、ch、sh、r 的发音', '能和平舌音区分', '会读常见卷舌词'],
        teachingSteps: ['观察舌尖轻卷，练习 zh、ch、sh、r。', '把 z-zh、c-ch、s-sh 放在一起对读。', '练读 zhi、chi、shi、ri 以及“热、车、书”。'],
        practiceWords: ['zhǐ 纸', 'chē 车', 'shū 书', 'rì 日'],
        practiceSentence: '日出时，小车送书去。',
        miniTask: '照镜子读 zhi chi shi ri，感受舌尖卷起。',
        checkpoints: ['知道 zh ch sh r 是卷舌音', '能和 z c s 区分', '会读 zhi、chi、shi、ri'],
      }),
      lesson('py-10', '整体认读音节入门', {
        tagline: '有些音节要整体记住，不再拆开慢慢拼。',
        focus: ['yi', 'wu', 'yu', 'ye', 'yue', 'yuan', 'yin', 'yun', 'ying'],
        goals: ['知道整体认读音节的概念', '能一口气读出常见整体认读音节', '会在词语中直接认读'],
        teachingSteps: ['认识“整体认读音节”就是见到就整体读。', '分类练读 yi、wu、yu 系列。', '在词语中练“月亮、云朵、影子、音乐”。'],
        practiceWords: ['yuè 月', 'yún 云', 'yǐng 影', 'yīn 音'],
        practiceSentence: '月亮下有云影。',
        miniTask: '把九个整体认读音节从头背到尾。',
        checkpoints: ['知道整体认读音节不用拆拼', '能读 yi wu yu ye yue', '能在词里认读 yin yun ying'],
      }),
    ],
  },
  {
    id: 'grade-1-advanced',
    title: '一年级下: 复韵母与拼读',
    description: '继续完成复韵母、鼻韵母和整体认读音节，建立一年级拼读闭环。',
    lessons: [
      lesson('py-11', '复韵母 ai ei ui', {
        tagline: '两个元音连起来，嘴型要自然滑动。',
        focus: ['ai', 'ei', 'ui'],
        goals: ['会读 ai、ei、ui', '能拼带这三组韵母的音节', '在生活词语里找到它们'],
        teachingSteps: ['体会 ai、ei、ui 都是从一个口型滑向另一个口型。', '练读 bai、mei、gui、dui。', '用“爱、杯、归”巩固。'],
        practiceWords: ['ài 爱', 'bēi 杯', 'guī 归', 'duì 对'],
        practiceSentence: '小龟回归大海。',
        miniTask: '连读 bai-bei-bui（注意 bui 不存在，感受区别）。',
        checkpoints: ['会读 ai ei ui', '能拼 bai、dui', '能说出 ui 读作“威”类口感'],
      }),
      lesson('py-12', '复韵母 ao ou iu', {
        tagline: '学会大开口到收口的滑动。',
        focus: ['ao', 'ou', 'iu'],
        goals: ['掌握 ao、ou、iu', '会读 bao、hou、liu', '能分清 iu 和 ui'],
        teachingSteps: ['练 ao、ou、iu 的口型滑动。', '比较 liu 和 dui 的结尾不同。', '用“高、口、牛”归类。'],
        practiceWords: ['gāo 高', 'kǒu 口', 'liú 流', 'hóu 猴'],
        practiceSentence: '小猴口渴要喝牛奶。',
        miniTask: '把 iu 和 ui 各举两个词。',
        checkpoints: ['能读 ao ou iu', '不会把 iu 和 ui 混淆', '会拼 liu、hou、gao'],
      }),
      lesson('py-13', '复韵母 ie üe er', {
        tagline: '继续认识前响复韵母和特殊音 er。',
        focus: ['ie', 'üe', 'er'],
        goals: ['会读 ie、üe、er', '会读 jue、xue、er', '认识 er 是特殊韵母'],
        teachingSteps: ['练 ie 与 üe 的区别，注意 üe 前仍有两点规则。', '认识 er 常常单独成音节。', '练读 jie、xue、er、ye。'],
        practiceWords: ['jiě 姐', 'xué 学', 'ér 儿', 'yè 叶'],
        practiceSentence: '姐姐学会画树叶。',
        miniTask: '读三遍 xue、yue、jue。',
        checkpoints: ['会读 ie üe er', '知道 xue 中的 u 实际读 ü', '能拼读 jie、xue'],
      }),
      lesson('py-14', '前鼻韵母 an en in un ün', {
        tagline: '鼻音收在前面，口腔要干净利落。',
        focus: ['an', 'en', 'in', 'un', 'ün'],
        goals: ['掌握前鼻韵母', '能读 ban、men、xin、lun、yun', '会听辨前鼻尾音 n'],
        teachingSteps: ['练习 n 收尾，让舌尖轻碰上齿龈。', '分类对读 an/en/in/un/ün。', '用“山、门、心、轮、云”巩固。'],
        practiceWords: ['shān 山', 'mén 门', 'xīn 心', 'yún 云'],
        practiceSentence: '云从山门前慢慢来。',
        miniTask: '把带 n 结尾的词语拍手读一轮。',
        checkpoints: ['知道是前鼻韵母', '能读准 an en in', '能分清 yun 属于整体认读音节'],
      }),
      lesson('py-15', '后鼻韵母 ang eng ing ong', {
        tagline: '鼻音拉到后面，舌根向后抬。',
        focus: ['ang', 'eng', 'ing', 'ong'],
        goals: ['掌握后鼻韵母', '会读 fang、deng、xing、dong', '能和前鼻韵母对比'],
        teachingSteps: ['感受 ang、eng、ing、ong 都是后鼻收尾。', '把 an-ang、en-eng、in-ing 做对比。', '用“房、灯、星、冬”练读。'],
        practiceWords: ['fáng 房', 'dēng 灯', 'xīng 星', 'dōng 冬'],
        practiceSentence: '冬天的星星像小灯。',
        miniTask: '读一遍 an-ang、en-eng、in-ing 对照组。',
        checkpoints: ['知道后鼻韵母收在后面', '能分辨 in 和 ing', '会拼 deng、xing、dong'],
      }),
      lesson('py-16', '整体认读音节总表', {
        tagline: '把整体认读音节一次性认全。',
        focus: ['zhi', 'chi', 'shi', 'ri', 'zi', 'ci', 'si', 'yi', 'wu', 'yu', 'ye', 'yue', 'yuan', 'yin', 'yun', 'ying'],
        goals: ['完整掌握 16 个整体认读音节', '能按类背诵', '能在阅读中快速识别'],
        teachingSteps: ['先按平舌、卷舌、y 系三组分类记忆。', '再从词语中抽出整体认读音节。', '用抢答方式提升认读速度。'],
        practiceWords: ['zhī 知', 'cí 词', 'yuán 圆', 'yīng 鹰'],
        practiceSentence: '小鹰知道圆月很亮。',
        miniTask: '试着把 16 个整体认读音节默写在纸上。',
        checkpoints: ['能说出共有 16 个', '能分类背诵', '能在词语中快速找到它们'],
      }),
      lesson('py-17', '标调规则', {
        tagline: '有 a 不放过，没 a 找 o e，i u 并列标在后。',
        focus: ['标调顺序', '省调位置'],
        goals: ['知道声调应该标在哪个韵母上', '会给常见音节标调', '能检查 iu/ui 的标调位置'],
        teachingSteps: ['背诵标调口诀并逐条举例。', '用 ai、ou、iu、ui 做标调练习。', '检查 xue、gui、liu 的标调位置。'],
        practiceWords: ['hǎi 海', 'shǒu 手', 'liú 流', 'guì 贵'],
        practiceSentence: '海水流向远处。',
        miniTask: '给 bao、mei、liu、gui 分别标上三声。',
        checkpoints: ['会背标调口诀', '不会把 iu/ui 标错', '会给复韵母音节标调'],
      }),
      lesson('py-18', '两拼与三拼音节', {
        tagline: '学会把声母、介母、韵母连成整块。',
        focus: ['两拼音节', '三拼音节', '介母 i/u/ü'],
        goals: ['会拼两拼音节', '理解三拼音节中介母的作用', '会读 gua、kuo、xuan 等音节'],
        teachingSteps: ['先复习声母 + 韵母的两拼方式。', '再用 gua、kuo、xuan 认识三拼音节。', '学会快速连读，不一节一节断开。'],
        practiceWords: ['guā 瓜', 'kuò 阔', 'xuán 旋', 'huā 花'],
        practiceSentence: '花园里有圆圆的瓜。',
        miniTask: '把 gua、hua、kuo、xuan 连读两轮。',
        checkpoints: ['会区分两拼和三拼', '知道介母是什么', '能顺畅读出 gua、hua、xuan'],
      }),
      lesson('py-19', '看拼音读词语', {
        tagline: '把前面的知识真正用到识词上。',
        focus: ['词语认读', '音节连贯'],
        goals: ['能独立读出双音节词', '会把音节连成词而不是逐个字母念', '提高认读速度'],
        teachingSteps: ['练读“学校、月亮、草地、树林”等词。', '从慢速拼读逐步过渡到整体认读。', '用计时方式挑战 1 分钟读词。'],
        practiceWords: ['xué xiào 学校', 'yuè liang 月亮', 'cǎo dì 草地', 'shù lín 树林'],
        practiceSentence: '学校旁边有一片树林。',
        miniTask: '把四个双音节词连续读三遍。',
        checkpoints: ['能读双音节词', '读词比单字更连贯', '不会漏读声调'],
      }),
      lesson('py-20', '一年级拼音总复习', {
        tagline: '把一年级拼音知识串成一个完整网络。',
        focus: ['声母', '韵母', '整体认读', '拼读应用'],
        goals: ['完成一年级知识盘点', '找到易错点', '能读带拼音的小短文'],
        teachingSteps: ['回顾声母、韵母和整体认读音节。', '专项检查易混音：z/zh、c/ch、s/sh、in/ing。', '朗读一段带拼音的校园小短文。'],
        practiceWords: ['zhōng guó 中国', 'huā yuán 花园', 'yǐng zi 影子', 'shēng yīn 声音'],
        practiceSentence: '花园里的影子跟着声音跳舞。',
        miniTask: '把自己最容易错的三组音写在学习卡上。',
        checkpoints: ['能完成一年级拼音回顾', '知道自己的易错点', '能读拼音短文'],
      }),
    ],
  },
  {
    id: 'grade-2-application',
    title: '二年级: 拼音应用与纠错',
    description: '重点处理变调、轻声、易混音和查字典，让拼音真正服务识字与朗读。',
    lessons: [
      lesson('py-21', '轻声', {
        tagline: '有些音节要轻轻地读，像小尾巴一样跟着前面。',
        focus: ['轻声', '词语节奏'],
        goals: ['认识轻声', '会读常见轻声词', '能在口语里自然读出轻重变化'],
        teachingSteps: ['对比“妈妈、我们、东西”的后一个音节。', '练习重音节 + 轻声音节的节奏。', '在句子里朗读“桌子上有东西”。'],
        practiceWords: ['mā ma 妈妈', 'wǒ men 我们', 'dōng xi 东西', 'zhuō zi 桌子'],
        practiceSentence: '桌子上有我们的东西。',
        miniTask: '找两个家里常说的轻声词。',
        checkpoints: ['知道轻声不是第五声乱读', '会读常见轻声词', '句子里读得更自然'],
      }),
      lesson('py-22', '三声连读', {
        tagline: '两个三声连在一起，前一个要先变成二声。',
        focus: ['三声变调', '词语朗读'],
        goals: ['掌握两个三声连读规则', '会读“你好、雨伞、老板”等词', '能在句子中自然应用'],
        teachingSteps: ['用“你好、雨伞、老师”示范三声连读。', '听辨前一个三声变成二声后的感觉。', '在短句里练“你好，我们一起走”。'],
        practiceWords: ['nǐ hǎo 你好', 'yǔ sǎn 雨伞', 'lǎo shī 老师', 'xiǎo jiě 小姐'],
        practiceSentence: '你好，老师请你拿雨伞。',
        miniTask: '把四个双三声词读顺，注意第一个音节抬起来。',
        checkpoints: ['知道两个三声相连怎么读', '能读准你好', '句子里不会卡顿'],
      }),
      lesson('py-23', '“不”和“一”的变调', {
        tagline: '常见字也有“看邻居变声音”的情况。',
        focus: ['不的变调', '一的变调'],
        goals: ['掌握“不”在四声前变二声', '掌握“一”在不同声调前的变化', '会读常见句式'],
        teachingSteps: ['对比“不对、不行、不是”。', '练“一天、一朵、一样、第一”。', '把规则放到句子里朗读。'],
        practiceWords: ['bú duì 不对', 'yí tiān 一天', 'yì duǒ 一朵', 'dì yī 第一'],
        practiceSentence: '一天一朵花，不是第一也没关系。',
        miniTask: '各说出一个“bú”和“yí/yì”的词。',
        checkpoints: ['知道不在四声前读 bú', '知道一会变 yí / yì', '会在句子里自然运用'],
      }),
      lesson('py-24', '儿化音', {
        tagline: '北京话和口语里常见的“小尾巴”。',
        focus: ['儿化', '口语表达'],
        goals: ['认识儿化音', '会读常见儿化词', '知道儿化不是把“儿”单独拖长'],
        teachingSteps: ['听“花儿、门儿、玩儿”并模仿。', '体会儿化前后词语感觉变化。', '在口语句子中练读。'],
        practiceWords: ['huār 花儿', 'ménr 门儿', 'wánr 玩儿', 'kōngr 空儿'],
        practiceSentence: '一会儿咱们去门口玩儿。',
        miniTask: '跟读三遍“花儿、鸟儿、玩儿”。',
        checkpoints: ['知道什么是儿化', '会读 2-3 个常见儿化词', '不会把儿化拆成两个字去读'],
      }),
      lesson('py-25', '隔音符号与大写规则', {
        tagline: '遇到音节边界模糊时，要请隔音符号帮忙。',
        focus: ['隔音符号', '专名大写'],
        goals: ['知道什么时候使用隔音符号', '认识拼音大写的基本场景', '会读西安、方案等容易混的词'],
        teachingSteps: ['比较 xian 和 Xi\'an 的读法。', '认识人名、地名首字母大写。', '练“西安、平安、方案、海鸥”。'],
        practiceWords: ['Xī\'ān 西安', 'hǎi\'ōu 海鸥', 'Péng Péng 鹏鹏', 'Běijīng 北京'],
        practiceSentence: '北京的小朋友去了西安。',
        miniTask: '写出一个需要隔音符号的拼音词。',
        checkpoints: ['知道隔音符号长什么样', '能说出西安为什么要加符号', '知道专名首字母要大写'],
      }),
      lesson('py-26', '音序查字典', {
        tagline: '拼音不仅能读，还能帮你查字典。',
        focus: ['音序', '大写字母', '字典查询'],
        goals: ['认识音序表', '知道按首字母查字', '会找常见字的大写音序'],
        teachingSteps: ['复习 A-Z 的音序顺序。', '从“河、书、校、云”找出 H、S、X、Y。', '模拟查字典先看音序再找音节。'],
        practiceWords: ['河 H', '书 S', '校 X', '云 Y'],
        practiceSentence: '先找音序，再找音节。',
        miniTask: '把你名字里第一个字的音序找出来。',
        checkpoints: ['知道音序是大写字母', '会按首字母查找', '能说出常见字的音序'],
      }),
      lesson('py-27', '易混声母辨析', {
        tagline: '把常见的“长得像、听着像”声母彻底分开。',
        focus: ['b/d', 'p/q', 'n/l', 'z/zh'],
        goals: ['能辨析常见易混声母', '会用口型和位置自检', '减少拼读错误'],
        teachingSteps: ['逐组比较 b/d、p/q 的书写和发音。', '重点练 n/l、z/zh 的口腔位置。', '用最小对立词做听辨。'],
        practiceWords: ['bǐ 笔 / dǐ 底', 'píng 平 / qíng 情', 'niú 牛 / liú 流', 'zǐ 子 / zhǐ 纸'],
        practiceSentence: '纸和子，牛和流，要听清也要看清。',
        miniTask: '挑出自己最容易混的一组，单独读五遍。',
        checkpoints: ['知道自己的易混组', '能用发音位置解释差别', '读词时更稳定'],
      }),
      lesson('py-28', '易混韵母辨析', {
        tagline: '前鼻音、后鼻音和复韵母经常“长得像”。',
        focus: ['ie/ei', 'iu/ui', 'in/ing', 'en/eng'],
        goals: ['能区分易混韵母', '会通过口型和鼻尾判断', '能在词语中稳定认读'],
        teachingSteps: ['逐组比较 ie/ei、iu/ui。', '重点练前后鼻音 in/ing、en/eng。', '在词语中做分类朗读。'],
        practiceWords: ['jiě 姐 / běi 北', 'liú 流 / guī 归', 'xīn 心 / xīng 星', 'mén 门 / mēng 蒙'],
        practiceSentence: '心和星、门和蒙，尾音一定要听清。',
        miniTask: '把 in-ing、en-eng 做成两列读一轮。',
        checkpoints: ['不会把 in 读成 ing', '知道 iu 和 ui 的差别', '能从词语里听出正确韵母'],
      }),
      lesson('py-29', '看拼音写词语', {
        tagline: '从“读得出”走向“写得出”。',
        focus: ['听写', '拼音转词语', '声调保留'],
        goals: ['会根据拼音写常见词语', '能注意声调提示', '知道先整体读词再写字'],
        teachingSteps: ['读拼音词组，再说中文词义。', '练“春天、朋友、学校、快乐”等常见词。', '总结写词时先读顺再落笔。'],
        practiceWords: ['chūn tiān 春天', 'péng yǒu 朋友', 'xué xiào 学校', 'kuài lè 快乐'],
        practiceSentence: '春天来了，朋友一起去学校。',
        miniTask: '闭眼听读两个拼音词，再尝试写出来。',
        checkpoints: ['能根据拼音写常见词', '不会忽略声调提示', '知道先整体读词'],
      }),
      lesson('py-30', '二年级拼音阅读', {
        tagline: '把规则带进完整短文里。',
        focus: ['短文朗读', '停顿', '变调综合'],
        goals: ['能较流畅地读带拼音短文', '会在句号逗号处停顿', '在真实语境中应用轻声和变调'],
        teachingSteps: ['朗读一段关于春游的拼音短文。', '标出需要停顿和变调的地方。', '尝试用自己的话复述内容。'],
        practiceWords: ['chūn yóu 春游', 'shān pō 山坡', 'yuè liàng 月亮', 'lǎo shī 老师'],
        practiceSentence: '老师带我们去山坡春游。',
        miniTask: '读完短文后，用一句话说出主角做了什么。',
        checkpoints: ['能读短文不逐字拆拼', '会停顿', '能复述主要内容'],
      }),
    ],
  },
  {
    id: 'grade-3-integration',
    title: '三年级: 综合阅读与表达',
    description: '把拼音用于阅读、表达和写作辅助，完成 1-3 年级的完整覆盖。',
    lessons: [
      lesson('py-31', '多音节词切分', {
        tagline: '长一点的词语也能被拼音稳稳托住。',
        focus: ['多音节词', '节奏切分'],
        goals: ['会读三到四个音节的词语', '知道按词义而不是机械分段', '提升朗读流畅度'],
        teachingSteps: ['练“图书馆、科学家、运动会”等多音节词。', '按词义切分，不逐个音节拖读。', '尝试在词语里找到重音位置。'],
        practiceWords: ['tú shū guǎn 图书馆', 'kē xué jiā 科学家', 'yùn dòng huì 运动会', 'huán jìng bǎo hù 环境保护'],
        practiceSentence: '科学家来到图书馆做分享。',
        miniTask: '选一个四音节词，先慢读再快读。',
        checkpoints: ['能读三四音节词', '会按词义切分', '朗读更连贯'],
      }),
      lesson('py-32', '看拼音写句子', {
        tagline: '拼音成为句子表达的脚手架。',
        focus: ['拼音写句', '标点意识'],
        goals: ['会把拼音句子写成汉字句', '能保留句意和标点', '知道先理解再书写'],
        teachingSteps: ['读拼音句子并说出意思。', '练习“今天我们一起种花”“小鸟在树上唱歌”。', '检查句末标点和专名。'],
        practiceWords: ['jīn tiān 今天', 'yì qǐ 一起', 'zhòng huā 种花', 'chàng gē 唱歌'],
        practiceSentence: '今天我们一起种花，小鸟在树上唱歌。',
        miniTask: '把一句拼音句改写成自己的句子。',
        checkpoints: ['能把拼音句转成汉字句', '不漏词', '注意标点'],
      }),
      lesson('py-33', '短文朗读停顿', {
        tagline: '读文章时，停顿和语气比拼得快更重要。',
        focus: ['停顿', '重音', '语气'],
        goals: ['会在短文中按意群停顿', '能读出问句和陈述句', '提升朗读理解'],
        teachingSteps: ['在短文里用斜线标出停顿位置。', '练习问句、感叹句和陈述句不同语气。', '两遍朗读比较：一遍匀速，一遍按意群。'],
        practiceWords: ['zěn me 怎么', 'yuán lái 原来', 'zhēn de 真的', 'měi lì 美丽'],
        practiceSentence: '原来，花园真的这么美丽！',
        miniTask: '把一句话分别用疑问语气和感叹语气读出来。',
        checkpoints: ['知道意群停顿', '会区分语气', '朗读更像说话'],
      }),
      lesson('py-34', '古诗拼音朗读', {
        tagline: '拼音帮助古诗入门，节奏和押韵更重要。',
        focus: ['古诗节奏', '押韵', '停顿'],
        goals: ['能借助拼音朗读古诗', '知道古诗常见停顿方式', '感受韵脚和节奏'],
        teachingSteps: ['选一首适合低年级的古诗做拼音朗读。', '按“二二一”或“二二三”节奏试读。', '找出句末押韵的字。'],
        practiceWords: ['míng yuè 明月', 'gù xiāng 故乡', 'chuáng qián 床前', 'yè sè 夜色'],
        practiceSentence: '床前明月光，疑是地上霜。',
        miniTask: '给古诗每句末尾的字做个韵脚记号。',
        checkpoints: ['能借助拼音读古诗', '会按节奏停顿', '知道什么是押韵'],
      }),
      lesson('py-35', '综合阅读与复述', {
        tagline: '读完以后还能说出来，拼音就真正变成工具了。',
        focus: ['阅读理解', '复述', '关键词提取'],
        goals: ['能读一篇带拼音短文', '能说出时间、地点、人物、事情', '会抓关键词复述'],
        teachingSteps: ['朗读一篇“去植物园”的短文。', '找出时间、地点、人物、做了什么。', '用 3 句话复述内容。'],
        practiceWords: ['zhí wù yuán 植物园', 'guān chá 观察', 'jì lù 记录', 'huí jiā 回家'],
        practiceSentence: '我们去植物园观察花草，还认真做了记录。',
        miniTask: '用“先……再……最后……”复述短文。',
        checkpoints: ['能提取关键信息', '能复述主要内容', '朗读和理解开始结合'],
      }),
      lesson('py-36', '三年级拼音闯关', {
        tagline: '把 1-3 年级内容全部串联起来，完成毕业关。',
        focus: ['综合检测', '纠错回看', '学习总结'],
        goals: ['完成全课程收尾', '知道自己最稳和最弱的部分', '能给自己制定下一轮复习计划'],
        teachingSteps: ['用声母、韵母、变调、阅读四个维度自检。', '回做自己最容易错的 5 组音。', '写一张“我的拼音通关卡”。'],
        practiceWords: ['yīn jié 音节', 'biàn diào 变调', 'yuè dú 阅读', 'zǒng jié 总结'],
        practiceSentence: '我已经能用拼音帮助自己阅读和复习。',
        miniTask: '写下三项你已经会的内容和一项还要再练的内容。',
        checkpoints: ['能回顾全部课程', '知道自己的薄弱点', '具备继续复习的路径'],
      }),
    ],
  },
];

function buildCurriculum() {
  let order = 1;

  return curriculumStages.map((stage, stageIndex) => {
    const lessons = stage.lessons.map((item, lessonIndex) => ({
      ...item,
      order: order++,
      stageId: stage.id,
      stageTitle: stage.title,
      stageIndex: stageIndex + 1,
      stageLessonIndex: lessonIndex + 1,
    }));

    return {
      ...stage,
      lessonCount: lessons.length,
      estimatedMinutes: lessons.reduce((total, item) => total + item.durationMinutes, 0),
      lessons,
    };
  });
}

const stages = buildCurriculum();
const lessons = stages.flatMap((stage) => stage.lessons);
const lessonMap = new Map(lessons.map((item) => [item.id, item]));

function getCurriculumStages() {
  return stages;
}

function getCurriculumLessons() {
  return lessons;
}

function getLessonById(lessonId) {
  return lessonMap.get(lessonId) || null;
}

module.exports = {
  getCurriculumLessons,
  getCurriculumStages,
  getLessonById,
};
