function lesson(id, title, options) {
  return {
    id,
    title,
    durationMinutes: 12,
    ...options,
  };
}

function createAsset(label, solution) {
  return {
    label,
    status: 'pending',
    solution,
  };
}

function createStep(id, title, options) {
  return {
    id,
    title,
    teacherPrompt: '',
    tvScene: '',
    controllerScene: '',
    interaction: '',
    feedback: '',
    controllerMode: 'tap',
    highlights: [],
    resources: [],
    ...options,
  };
}

function createStage(id, title, summary, steps) {
  return {
    id,
    title,
    summary,
    steps,
  };
}

function createGenericFlow(spec) {
  return [
    createStage('fun-ear', '趣味导入：磨耳朵', `先把 ${spec.focusLabel} 的声音和情境连起来。`, [
      createStep('warmup', spec.introTitle || '情境唤醒', {
        teacherPrompt: spec.introPrompt,
        tvScene: spec.introTvScene,
        controllerScene: spec.introControllerScene,
        interaction: spec.introInteraction,
        feedback: spec.introFeedback,
        controllerMode: spec.introMode || 'tap',
        highlights: spec.introHighlights || [spec.focusLabel],
        resources: spec.introResources || [],
      }),
    ]),
    createStage('core-look-read', '核心教学：看与读', `先看口型和形状，再把 ${spec.focusLabel} 稳稳读出来。`, [
      createStep('sound', spec.coreSoundTitle || '读准音', {
        teacherPrompt: spec.coreSoundPrompt,
        tvScene: spec.coreSoundTvScene,
        controllerScene: spec.coreSoundControllerScene,
        interaction: spec.coreSoundInteraction,
        feedback: spec.coreSoundFeedback,
        controllerMode: spec.coreSoundMode || 'voice',
        highlights: spec.coreSoundHighlights || [],
        resources: spec.coreSoundResources || [],
      }),
      createStep('shape', spec.coreShapeTitle || '识记形', {
        teacherPrompt: spec.coreShapePrompt,
        tvScene: spec.coreShapeTvScene,
        controllerScene: spec.coreShapeControllerScene,
        interaction: spec.coreShapeInteraction,
        feedback: spec.coreShapeFeedback,
        controllerMode: spec.coreShapeMode || 'spotlight',
        highlights: spec.coreShapeHighlights || [],
        resources: spec.coreShapeResources || [],
      }),
    ]),
    createStage('play-learn', '互动巩固：玩中学', `通过互动任务把 ${spec.focusLabel} 记得更牢。`, [
      createStep('game-1', spec.gameOneTitle || '听音选择', {
        teacherPrompt: spec.gameOnePrompt,
        tvScene: spec.gameOneTvScene,
        controllerScene: spec.gameOneControllerScene,
        interaction: spec.gameOneInteraction,
        feedback: spec.gameOneFeedback,
        controllerMode: spec.gameOneMode || 'choices',
        highlights: spec.gameOneHighlights || [],
        resources: spec.gameOneResources || [],
      }),
      createStep('game-2', spec.gameTwoTitle || '闯关练习', {
        teacherPrompt: spec.gameTwoPrompt,
        tvScene: spec.gameTwoTvScene,
        controllerScene: spec.gameTwoControllerScene,
        interaction: spec.gameTwoInteraction,
        feedback: spec.gameTwoFeedback,
        controllerMode: spec.gameTwoMode || 'joystick',
        highlights: spec.gameTwoHighlights || [],
        resources: spec.gameTwoResources || [],
      }),
    ]),
    createStage('write-review', '总结闭环：写与复习', `通过书写、奖励和预告收住本课节奏。`, [
      createStep('wrap-up', spec.wrapTitle || '跟写复盘', {
        teacherPrompt: spec.wrapPrompt,
        tvScene: spec.wrapTvScene,
        controllerScene: spec.wrapControllerScene,
        interaction: spec.wrapInteraction,
        feedback: spec.wrapFeedback,
        controllerMode: spec.wrapMode || 'trace',
        highlights: spec.wrapHighlights || [],
        resources: spec.wrapResources || [],
      }),
    ]),
  ];
}

function buildLesson(spec) {
  const teachingFlow = spec.teachingFlow || createGenericFlow(spec);

  return lesson(spec.id, spec.title, {
    tagline: spec.tagline,
    focus: spec.focus,
    goals: spec.goals,
    practiceWords: spec.practiceWords,
    practiceSentence: spec.practiceSentence,
    miniTask: spec.miniTask,
    checkpoints: spec.checkpoints,
    lessonType: spec.lessonType,
    lessonBadge: spec.lessonBadge,
    previewLesson: spec.previewLesson,
    assetNotes: spec.assetNotes || [],
    teachingFlow,
  });
}

const commonAssetPlan = [
  createAsset('角色插画与场景图', '先用 CSS 图形和渐变占位，后续可接入 SVG 插画或 AI 生成插画。'),
  createAsset('老师口型视频 / 数字人口播', '先展示静态口型示意卡，后续接入实拍视频或数字人口型素材。'),
  createAsset('音效与儿歌配音', '先保留文案与提示位，后续把 mp3 放到静态资源目录并由展示端播放。'),
];

const lesson01 = buildLesson({
  id: 'py-01',
  title: '单韵母 a',
  lessonType: '单韵母',
  lessonBadge: '示范课模板',
  tagline: '用摇一摇、开口读、滑梯声调和跟写，把 a 变成第一节沉浸式拼音课。',
  focus: ['a', '张大嘴巴', '四声调', '四线三格'],
  goals: ['能听到并模仿 a 的发音', '能把字形和“小女孩扎辫子”联想起来', '能完成 a 的跟读、点选和跟写'],
  practiceWords: ['ā 阿姨', 'á 啊？', 'ǎ 啊哈', 'à 啊！'],
  practiceSentence: '张大嘴巴，跟着老师把 a 读得又亮又长。',
  miniTask: '下课前请再读一遍 ā á ǎ à，并在空中比划一次 a 的笔顺。',
  checkpoints: ['孩子能主动张嘴发 a', '能认出 a 的字形和四声调', '能跟着四线三格写出两笔'],
  previewLesson: '下一节预告：大公鸡 o',
  assetNotes: commonAssetPlan,
  teachingFlow: [
    createStage('fun-ear', '趣味导入：磨耳朵', '通过摇一摇唤醒小公鸡，把孩子带进 a 的声音情境。', [
      createStep('wake-rooster', '摇铃唤醒小公鸡', {
        teacherPrompt: '小朋友，快摇一摇手机，叫醒小公鸡和我们一起学拼音吧！',
        tvScene: '电视画面是宁静的小村庄，清晨太阳升起，大公鸡站在篱笆上准备打鸣。',
        controllerScene: '手机中央出现一个巨大的金色铃铛，四周有轻微闪光提示孩子开始动作。',
        interaction: '孩子摇动手机后，电视里的公鸡拍动翅膀发出“喔喔”声，画面中央蹦出一个大大的红色 a。',
        feedback: '电视随后播放儿歌提示：“圆圆脸蛋扎小辫，张大嘴巴 a a a。”',
        controllerMode: 'shake',
        highlights: ['摇一摇', '公鸡打鸣', '红色 a'],
        resources: [
          createAsset('公鸡叫声音效', '可先接入短音效文件，后续再补更完整的环境声。'),
          createAsset('小村庄与大公鸡插画', '先做插画占位，后续补精细资源。'),
        ],
      }),
    ]),
    createStage('core-look-read', '核心教学：看与读', '先读准音，再把字母外形和图像记忆绑定起来。', [
      createStep('mouth-a', '读准音', {
        teacherPrompt: '张大嘴巴，感受嗓子用力，轮到你大声喊 a 了。',
        tvScene: '电视展示漂亮姐姐的发音口型，含正面和侧面两个视角，并伴随气流流动动画。',
        controllerScene: '手机出现一个大大的麦克风图标，周围光圈闪烁，提示可以开口。',
        interaction: '电视提示“轮到你了”，手机轻轻震动。孩子对着手机喊“a——”，电视上的小气球随着声音高低上下起伏。',
        feedback: '大屏给出“嘴巴张得真大，声音真亮”的正向反馈，并保留口型示意。',
        controllerMode: 'voice',
        highlights: ['口型示范', '麦克风', '气球跟声调动'],
      }),
      createStep('shape-a', '识记形', {
        teacherPrompt: '看看 a 像什么，把圆脸和小辫子一起记住。',
        tvScene: '电视上出现一个可爱的小女孩头像叠加在字母 a 上，圆脸对应左半圆，辫子对应右边的竖弯。',
        controllerScene: '手机变成探照灯，手指滑到哪里，电视上的对应结构就会亮起来。',
        interaction: '孩子拖动探照灯，依次照亮左半圆和右竖弯，电视同步高亮，并显示“先圆脸，再小辫”。',
        feedback: '字母 a 完整发光定格，帮助孩子把图像和字形建立联想。',
        controllerMode: 'spotlight',
        highlights: ['左半圆', '右竖弯', '圆脸扎小辫'],
      }),
    ]),
    createStage('play-learn', '互动巩固：玩中学', '通过声调和识别游戏，把刚学到的内容立即用起来。', [
      createStep('tones-a', '四声调滑梯', {
        teacherPrompt: '听老师念“阿姨的 ā”，请在手机上点选正确的声调。',
        tvScene: '电视展示四段滑梯：平地 ā、上坡 á、拐弯 ǎ、下坡 à，一辆小车停在起点。',
        controllerScene: '手机上出现 1、2、3、4 四个大按钮，每个按钮上方标有对应的声调符号。',
        interaction: '孩子点击正确声调后，小车沿着对应滑梯冲刺前进，同时播放匹配的 a 声调配音。',
        feedback: '答对后出现闪光和“你选对啦”，答错则提示再听一次。',
        controllerMode: 'choices',
        highlights: ['四声调', '滑梯', '数字按钮'],
      }),
      createStep('mushroom-a', '采蘑菇游戏', {
        teacherPrompt: '帮小兔只去踩写着 a 的蘑菇，别被别的字母骗到。',
        tvScene: '森林草地上散落许多字母蘑菇，包括 a、o、e，兔子站在起点。',
        controllerScene: '手机变成简易方向键或小摇杆，用来控制兔子前进。',
        interaction: '孩子控制兔子去踩 a 蘑菇，踩对会收集星星，踩错会响起“叮咚”干扰音。',
        feedback: '收集完成后，大屏回顾“今天我们抓到了好多 a”。',
        controllerMode: 'joystick',
        highlights: ['字母辨认', '兔子收集', '踩错干扰音'],
      }),
    ]),
    createStage('write-review', '总结闭环：写与复习', '在四线三格里完成跟写，并用奖励和预告收尾。', [
      createStep('write-a', '跟着魔法笔写 a', {
        teacherPrompt: '请跟随电视里的魔法笔写一写，先左半圆，再写竖弯。',
        tvScene: '电视放大显示标准拼音四线三格，一只魔法笔缓缓写出两笔：1. 左半圆，2. 竖弯。',
        controllerScene: '手机横屏显示带辅助线的四线三格，提示孩子跟着电视一起描写。',
        interaction: '孩子在手机上画笔迹，电视实时同步闪光线条。写完后屏幕撒下礼花，显示本节课获得“3 枚金牌”。',
        feedback: '大屏最后自动播放 5 秒“下一节大公鸡 o”的悬念预告。',
        controllerMode: 'trace',
        highlights: ['四线三格', '左半圆', '竖弯', '3 枚金牌'],
      }),
    ]),
  ],
});

function createPhonicsLesson(spec) {
  return buildLesson({
    ...spec,
    assetNotes: commonAssetPlan,
  });
}

const stageOneLessons = [
  lesson01,
  createPhonicsLesson({
    id: 'py-02',
    title: '单韵母 o',
    lessonType: '单韵母',
    lessonBadge: '第 2 课',
    tagline: '用圆嘴巴、回音山谷和转盘滑梯，把 o 的音和形同时记住。',
    focus: ['o', '圆唇', '回音感', '四声'],
    goals: ['能做出圆嘴口型', '能分辨 o 和 a 的不同', '能跟读 o 的四个声调'],
    practiceWords: ['ō 公鸡喔', 'ó 哦？', 'ǒ 哦！', 'ò 哦。'],
    practiceSentence: '嘴巴圆圆，声音向前送出 o。',
    miniTask: '对着镜子摆出圆嘴巴，再读两遍 ō ó ǒ ò。',
    checkpoints: ['孩子能做出圆嘴', '能读出 o 的回音感', '能在互动题里找出 o'],
    previewLesson: '下一节预告：大白鹅 e',
    introTitle: '点亮喇叭花',
    introPrompt: '轻点手机上的喇叭花，让山谷里的 o 回荡起来。',
    introTvScene: '电视里是有回音的山谷，一朵喇叭花正随着晨风晃动。',
    introControllerScene: '手机中间出现会旋转的金色喇叭花按钮。',
    introInteraction: '孩子点亮按钮后，山谷里一圈圈声波扩散，中央浮出发光的 o。',
    introFeedback: '旁白提醒：“嘴巴圆圆 o o o，像个小圈真好认。”',
    coreSoundPrompt: '把嘴巴拢成小圆圈，声音别挤扁。',
    coreSoundTvScene: '电视展示老师正面和侧面的圆唇口型，旁边有嘴型缩放动画。',
    coreSoundControllerScene: '手机出现麦克风和圆环音量表。',
    coreSoundInteraction: '孩子读 o 时，电视上的圆环跟着声音一圈圈放大。',
    coreSoundFeedback: '系统提示“圆嘴巴做得很好”。',
    coreShapePrompt: '看看 o 是不是像一个完整的小圆圈。',
    coreShapeTvScene: '电视把 o 变成一个橙色小太阳圈，沿着轮廓缓慢发光。',
    coreShapeControllerScene: '手机变成描边笔，手指划过轮廓即可点亮对应区域。',
    coreShapeInteraction: '孩子顺时针滑动，电视同步完成整个圆环描边。',
    coreShapeFeedback: '描完后出现“o 像太阳小圆圈”。',
    gameOneTitle: '声调转盘',
    gameOnePrompt: '听音后点选对应的 o 声调。',
    gameOneTvScene: '电视上是四格转盘，四个方向分别写着 ō ó ǒ ò。',
    gameOneControllerScene: '手机出现四个大按钮，像遥控器一样分布。',
    gameOneInteraction: '答对后转盘转到对应声调，播出配音。',
    gameOneFeedback: '累计三次正确即可点亮一颗星。',
    gameTwoTitle: '找圆圈朋友',
    gameTwoPrompt: '控制小鸟飞过只带 o 音的云朵。',
    gameTwoTvScene: '天空中飘着写有 o、e、a 的白云，小鸟准备起飞。',
    gameTwoControllerScene: '手机是左右移动摇杆。',
    gameTwoInteraction: '孩子控制小鸟收集 o 云朵，避开其他字母云。',
    gameTwoFeedback: '收集结束后展示“今天认识了圆圆的 o”。',
    wrapPrompt: '跟着电视里的笔，写一个圆圆的 o。',
    wrapTvScene: '电视上的魔法笔在四线三格中一笔绕出完整的 o。',
    wrapControllerScene: '手机横屏显示单格描写板和轮廓引导线。',
    wrapInteraction: '孩子在手机上描完后，电视太阳圈闪光并发放 3 枚金币。',
    wrapFeedback: '5 秒预告提示“下一节，大白鹅 e 就要来了”。',
  }),
  createPhonicsLesson({
    id: 'py-03',
    title: '单韵母 e',
    lessonType: '单韵母',
    lessonBadge: '第 3 课',
    tagline: '用大白鹅、平嘴角和滑动识形，完成 e 的第一轮感知。',
    focus: ['e', '嘴角平平', '白鹅', '四声'],
    goals: ['能模仿 e 的口型', '能把 e 和鹅的形象连起来', '能进行 e 的跟读和点选'],
    practiceWords: ['ē 鹅', 'é 额', 'ě 恶心的ě', 'è 饿'],
    practiceSentence: '白鹅伸长脖子，慢慢读出 e。',
    miniTask: '读 e 的时候把嘴角轻轻向两边拉开。',
    checkpoints: ['孩子能读出 e', '能认出 e 的字形', '知道 e 和鹅有关'],
    previewLesson: '下一节预告：小蚂蚁 i',
    introTitle: '叫醒白鹅',
    introPrompt: '点一点水面上的羽毛，让白鹅游出来和你见面。',
    introTvScene: '电视画面是一片安静的池塘，晨雾里有一根轻轻飘动的白羽毛。',
    introControllerScene: '手机出现发光羽毛按钮。',
    introInteraction: '点亮后，白鹅划开水面游出，水面中央浮起蓝色 e。',
    introFeedback: '儿歌提示：“白鹅白鹅 e e e，嘴角平平笑一笑。”',
    coreSoundPrompt: '嘴巴稍稍打开，嘴角平平地向两边拉。',
    coreSoundTvScene: '电视端展示 e 的口型定格和气流方向箭头。',
    coreSoundControllerScene: '手机出现麦克风和嘴角拉伸小动画。',
    coreSoundInteraction: '孩子读 e 时，电视上的水纹会随着声音轻轻荡开。',
    coreSoundFeedback: '口型卡提示“像白鹅发声一样平稳”。',
    coreShapePrompt: '把 e 记成水里回头看的白鹅。',
    coreShapeTvScene: '字母 e 与白鹅头颈造型叠加显示。',
    coreShapeControllerScene: '手机探照灯滑过字母，电视端依次高亮“横线”和“半圆回头”。',
    coreShapeInteraction: '孩子拖动探照灯观察结构。',
    coreShapeFeedback: '结构完成后出现白鹅点头动画。',
    gameOneTitle: '鹅叫声调门',
    gameOnePrompt: '听老师念，选出正确的 e 声调。',
    gameOneTvScene: '四道小门分别写着 ē é ě è，白鹅站在门口。',
    gameOneControllerScene: '手机出现 4 个大门按钮。',
    gameOneInteraction: '点对后白鹅穿过对应小门。',
    gameOneFeedback: '连对 3 次点亮池塘灯。',
    gameTwoTitle: '捞字母泡泡',
    gameTwoPrompt: '只捞带 e 的泡泡，别捞错。',
    gameTwoTvScene: '池塘里冒出写有 e、o、i 的泡泡。',
    gameTwoControllerScene: '手机是左右划水控制条。',
    gameTwoInteraction: '孩子控制小网兜捞到 e 泡泡。',
    gameTwoFeedback: '收尾提示“你把 e 都找出来啦”。',
    wrapPrompt: '跟着魔法笔写 e，再念一遍白鹅口诀。',
    wrapTvScene: '电视展示 e 在四线三格中的标准写法。',
    wrapControllerScene: '手机横屏是单字描写板。',
    wrapInteraction: '孩子描写时，电视边写边出现白鹅轮廓光效。',
    wrapFeedback: '写完播放“下一节：小蚂蚁 i”。',
  }),
  createPhonicsLesson({
    id: 'py-04',
    title: '单韵母 i',
    lessonType: '单韵母',
    lessonBadge: '第 4 课',
    tagline: '从细细的尖嘴音出发，让 i 的读音、点和竖一眼记住。',
    focus: ['i', '尖嘴', '一点一竖', '四声'],
    goals: ['能做出 i 的口型', '知道 i 的字形由点和竖组成', '能跟读 i 的四声'],
    practiceWords: ['ī 衣', 'í 姨', 'ǐ 蚁', 'ì 意'],
    practiceSentence: '嘴角向两边展开，轻轻把 i 拉长。',
    miniTask: '先比一个“1”，再想起 i 的一竖一点。',
    checkpoints: ['能读准 i', '能认出 i 的点和竖', '能和 a、o、e 区分'],
    previewLesson: '下一节预告：小乌龟 u',
    introTitle: '点亮小萤火虫',
    introPrompt: '摇一摇手机，让细细的萤火虫排成 i。',
    introTvScene: '夜色里，一群小萤火虫在草地上慢慢闪烁。',
    introControllerScene: '手机上是一只会发光的小瓶子。',
    introInteraction: '摇动后萤火虫飞起来，排成一根细竖和一个亮点。',
    introFeedback: '旁白说：“细细长长 i i i，一点一竖真清晰。”',
    coreSoundPrompt: '嘴角向两边拉开，声音细一点。',
    coreSoundTvScene: '老师示范 i 的口型，旁边有嘴角拉伸动画。',
    coreSoundControllerScene: '手机出现麦克风和细线音条。',
    coreSoundInteraction: '孩子发 i 时，电视音条变长变亮。',
    coreSoundFeedback: '系统提示“尖嘴音读出来了”。',
    coreShapePrompt: '先记一竖，再记头上的一点。',
    coreShapeTvScene: '电视把 i 拆成一竖和一个小萤火点。',
    coreShapeControllerScene: '手机探照灯先照竖，再照点。',
    coreShapeInteraction: '孩子按顺序点亮结构。',
    coreShapeFeedback: '两部分合体为完整的 i。',
    gameOneTitle: '衣服声调衣架',
    gameOnePrompt: '听声音，把 i 的声调挂到正确衣架上。',
    gameOneTvScene: '四个衣架上分别挂着 ī í ǐ ì。',
    gameOneControllerScene: '手机有 4 个声调按钮。',
    gameOneInteraction: '点对后小衣服挂到对应衣架。',
    gameOneFeedback: '答对亮起一颗纽扣星星。',
    gameTwoTitle: '找小点点',
    gameTwoPrompt: '控制小蚂蚁只去收集带 i 的字母牌。',
    gameTwoTvScene: '草地上散落 i、u、ü 字母牌。',
    gameTwoControllerScene: '手机变成方向键。',
    gameTwoInteraction: '小蚂蚁收集 i 牌并避开其他韵母。',
    gameTwoFeedback: '收集结束后回顾“一竖一点就是 i”。',
    wrapPrompt: '描一描 i，别忘了最后点上小圆点。',
    wrapTvScene: '电视分两笔展示 i 的写法。',
    wrapControllerScene: '手机横屏显示描写格。',
    wrapInteraction: '孩子写完后，点点会变成一颗亮星。',
    wrapFeedback: '预告“下一节：小乌龟 u”。',
  }),
  createPhonicsLesson({
    id: 'py-05',
    title: '单韵母 u',
    lessonType: '单韵母',
    lessonBadge: '第 5 课',
    tagline: '用小乌龟出壳和弯弯桥面，把 u 的音形一起锁住。',
    focus: ['u', '圆唇', '弯弯桥', '四声'],
    goals: ['能读准 u', '能记住 u 的弯弯形状', '能完成 u 的听辨互动'],
    practiceWords: ['ū 乌', 'ú 无', 'ǔ 五', 'ù 物'],
    practiceSentence: '嘴巴拢起来，轻轻向前送出 u。',
    miniTask: '对着镜子圆唇读 u，再把手指弯成一个 u。',
    checkpoints: ['能读准 u', '能认出弯弯的 u', '能和 i、ü 区分'],
    previewLesson: '下一节预告：小鱼儿 ü',
    introTitle: '敲敲乌龟壳',
    introPrompt: '点一下小乌龟的壳，听听谁从里面唱 u。',
    introTvScene: '河边石头上趴着一只小乌龟，壳上有金色纹路。',
    introControllerScene: '手机中央出现一个发亮的龟壳按钮。',
    introInteraction: '点亮后乌龟探出头，河面升起一个蓝绿色 u。',
    introFeedback: '提示语：“弯弯小桥 u u u，圆唇往前送出去。”',
    coreSoundPrompt: '嘴巴拢圆，声音别散开。',
    coreSoundTvScene: '老师示范 u 的圆唇发音，旁边有唇形收拢动画。',
    coreSoundControllerScene: '手机有麦克风和圆弧音条。',
    coreSoundInteraction: '孩子发声时，电视上的小船沿着河面前进。',
    coreSoundFeedback: '系统反馈“圆唇做得很稳”。',
    coreShapePrompt: '看一看 u 像不像一座弯弯的小桥。',
    coreShapeTvScene: '电视把 u 变成桥洞和小路的组合图。',
    coreShapeControllerScene: '手机滑过桥左边和右边时，大屏同步亮起。',
    coreShapeInteraction: '孩子观察结构后，桥面整体发光。',
    coreShapeFeedback: '提示“弯弯两边合起来就是 u”。',
    gameOneTitle: '小船找声调',
    gameOnePrompt: '听音选对 u 的声调，让小船开到正确码头。',
    gameOneTvScene: '四个码头分别标着 ū ú ǔ ù。',
    gameOneControllerScene: '手机是 4 个码头按钮。',
    gameOneInteraction: '选对后小船驶向对应码头。',
    gameOneFeedback: '连续命中会出现水花奖励。',
    gameTwoTitle: '捡桥牌',
    gameTwoPrompt: '帮小乌龟只捡写着 u 的桥牌。',
    gameTwoTvScene: '草地上有 u、i、ü 三种桥牌。',
    gameTwoControllerScene: '手机方向键控制乌龟前进。',
    gameTwoInteraction: '孩子控制乌龟收集 u。',
    gameTwoFeedback: '收尾总结“今天记住了弯弯小桥 u”。',
    wrapPrompt: '跟着魔法笔写 u，写完再读一遍。',
    wrapTvScene: '电视按笔顺演示 u 在四线三格中的写法。',
    wrapControllerScene: '手机横屏显示描写线。',
    wrapInteraction: '孩子描写成功后，乌龟背壳亮起金边。',
    wrapFeedback: '预告“下一节：小鱼儿 ü”。',
  }),
  createPhonicsLesson({
    id: 'py-06',
    title: '单韵母 ü 与四声',
    lessonType: '单韵母',
    lessonBadge: '第 6 课',
    tagline: '把“鱼嘴巴”和头上两点记牢，同时完成六个单韵母收官。',
    focus: ['ü', '撮口音', '两点', '四声'],
    goals: ['能读准 ü', '知道两点不能忘', '会区分 u 和 ü'],
    practiceWords: ['ǖ 淤', 'ǘ 鱼', 'ǚ 雨', 'ǜ 玉'],
    practiceSentence: '小嘴巴往前撮，两点戴在头上就是 ü。',
    miniTask: '先做出鱼儿吐泡泡的嘴，再读两遍 ü。',
    checkpoints: ['孩子能读出 ü', '能认出头上两点', '能区分 u 和 ü'],
    previewLesson: '下一节预告：声母 b p m f',
    introTitle: '叫醒小鱼儿',
    introPrompt: '吹一口气，让池塘里的小鱼儿吐出 ü 泡泡。',
    introTvScene: '清澈池塘里一群小鱼在荷叶旁绕圈。',
    introControllerScene: '手机上出现一只发亮的泡泡喇叭。',
    introInteraction: '点亮后，小鱼吐出两个泡泡，泡泡和字母组合成 ü。',
    introFeedback: '口诀提示：“小鱼吐泡 ü ü ü，头上两点别丢去。”',
    coreSoundPrompt: '把嘴唇撮起来，像要吹泡泡一样。',
    coreSoundTvScene: '电视示范 ü 的撮口口型，并与 u 进行对比。',
    coreSoundControllerScene: '手机出现麦克风和 u/ü 对比卡。',
    coreSoundInteraction: '孩子读 ü 时，电视上的鱼泡泡越飘越高。',
    coreSoundFeedback: '系统提醒“这是带两点的 ü”。',
    coreShapePrompt: '先看弯弯的身体，再看头上的两点。',
    coreShapeTvScene: '电视把 ü 拆成 u 和头顶两个气泡。',
    coreShapeControllerScene: '手机探照灯先照主体，再照两点。',
    coreShapeInteraction: '孩子按顺序高亮结构。',
    coreShapeFeedback: '完成后出现“u 戴上两点就变 ü”。',
    gameOneTitle: '泡泡声调道',
    gameOnePrompt: '听音选对 ü 的声调。',
    gameOneTvScene: '四条泡泡水道分别标着 ǖ ǘ ǚ ǜ。',
    gameOneControllerScene: '手机 4 个大按钮对应四声。',
    gameOneInteraction: '答对后鱼儿沿着对应水道游过去。',
    gameOneFeedback: '连续正确点亮整片池塘。',
    gameTwoTitle: '分清 u 和 ü',
    gameTwoPrompt: '控制小鱼只去碰带两点的卡片。',
    gameTwoTvScene: '水里漂着 u、ü、i 三种卡片。',
    gameTwoControllerScene: '手机方向键控制小鱼游动。',
    gameTwoInteraction: '孩子只收集 ü 卡。',
    gameTwoFeedback: '完成后总结“六个单韵母都见过啦”。',
    wrapPrompt: '描出 ü 的身体，再补上两点。',
    wrapTvScene: '电视在四线三格中演示 ü 的写法与标调位置。',
    wrapControllerScene: '手机横屏显示带两点的描写板。',
    wrapInteraction: '孩子完成后，电视端洒下礼花并显示“单韵母毕业章”。',
    wrapFeedback: '预告“下一节进入声母：b p m f”。',
  }),
];

function createStageLesson(stageId, title, description, specs) {
  return {
    id: stageId,
    title,
    description,
    lessons: specs.map(buildLesson),
  };
}

function consonantSpec(id, title, badge, focus, promptText, previewLesson) {
  return {
    id,
    title,
    lessonType: '声母',
    lessonBadge: badge,
    tagline: `${focus.join('、')} 放在一个游戏场景里学，重点是读准、分清、敢开口。`,
    focus,
    goals: [`能读出 ${focus.join('、')}`, '能在互动里区分易混项', '能和单韵母拼出基础音节'],
    practiceWords: focus.map((item) => `${item} 音卡`),
    practiceSentence: promptText,
    miniTask: `课后把 ${focus.join('、')} 连读两轮，再任选一个音节大声读给家长听。`,
    checkpoints: [`会读 ${focus.join('、')}`, '知道本课最容易混的地方', '能参与拼读游戏'],
    previewLesson,
    assetNotes: commonAssetPlan,
    introPrompt: `跟着节奏点亮舞台，把 ${focus.join('、')} 的字母演员请出来。`,
    introTvScene: `电视端是一座小舞台，${focus.join('、')} 对应的字母演员躲在幕布后面。`,
    introControllerScene: '手机出现发光节拍器按钮。',
    introInteraction: `孩子点击或摇动后，舞台灯光扫过，${focus.join('、')} 依次跳到中央。`,
    introFeedback: `旁白提示：“今天要认识 ${focus.join('、')} 这组新朋友。”`,
    coreSoundPrompt: `注意老师示范的口型和气流，把 ${focus.join('、')} 读清楚。`,
    coreSoundTvScene: `电视展示 ${focus.join('、')} 的口型对比卡和送气提示。`,
    coreSoundControllerScene: '手机出现麦克风和节奏光圈。',
    coreSoundInteraction: `孩子跟读时，大屏会给每个字母点亮对应音轨。`,
    coreSoundFeedback: '系统给出“读准了”“再试一次”的即时提示。',
    coreShapePrompt: `把 ${focus.join('、')} 的字形特征和动作记忆连起来。`,
    coreShapeTvScene: `电视把 ${focus.join('、')} 做成动作卡片，显示每个字母的关键笔画。`,
    coreShapeControllerScene: '手机变成探照灯，滑到哪里哪里亮。',
    coreShapeInteraction: '孩子逐个观察字母结构与动作联想。',
    coreShapeFeedback: '所有卡片点亮后形成完整组合。',
    gameOneTitle: '拼读出发台',
    gameOnePrompt: `听老师念音节，选出应该出场的 ${focus.join(' / ')}。`,
    gameOneTvScene: '电视显示起跑道，正确字母会把小车送到终点。',
    gameOneControllerScene: '手机显示多个大按钮，按钮上是本课字母。',
    gameOneInteraction: '选对后，小车沿着对应轨道冲出去。',
    gameOneFeedback: '答对累计星星，答错则重复示范音。',
    gameTwoTitle: '目标采集',
    gameTwoPrompt: `控制角色只去收集本课的 ${focus.join('、')} 字母牌。`,
    gameTwoTvScene: '电视场景中散落着本课字母和干扰字母。',
    gameTwoControllerScene: '手机变成方向键或摇杆。',
    gameTwoInteraction: '孩子控制角色寻找目标字母并躲开干扰项。',
    gameTwoFeedback: '收集完成后，大屏回顾本课字母清单。',
    wrapPrompt: `跟着电视复盘 ${focus.join('、')} 的关键写法，再念一遍。`,
    wrapTvScene: '电视在四线三格中依次演示本课字母的标准写法。',
    wrapControllerScene: '手机横屏显示描写格和轮廓辅助线。',
    wrapInteraction: '孩子选一个最有把握的字母描写同步到电视。',
    wrapFeedback: `写完会弹出奖励徽章，并预告“${previewLesson}”。`,
  };
}

const stageTwoLessons = [
  consonantSpec('py-07', '声母 b p m f', '第 7 课', ['b', 'p', 'm', 'f'], '把手放在嘴前，感受 b 和 p 的送气差别。', '下一节预告：声母 d t n l'),
  consonantSpec('py-08', '声母 d t n l', '第 8 课', ['d', 't', 'n', 'l'], '舌尖轻碰上齿龈，练出 d t n l 的位置感。', '下一节预告：声母 g k h'),
  consonantSpec('py-09', '声母 g k h', '第 9 课', ['g', 'k', 'h'], '把舌根抬起来，读出后舌根的力量。', '下一节预告：声母 j q x'),
  consonantSpec('py-10', '声母 j q x', '第 10 课', ['j', 'q', 'x'], '注意舌面靠前，感受更轻更尖的摩擦。', '下一节预告：声母 z c s'),
  consonantSpec('py-11', '声母 z c s', '第 11 课', ['z', 'c', 's'], '平舌音要放平，别把舌尖卷起来。', '下一节预告：声母 zh ch sh r'),
  consonantSpec('py-12', '声母 zh ch sh r', '第 12 课', ['zh', 'ch', 'sh', 'r'], '卷舌音要往后卷，和 z c s 拉开差距。', '下一节预告：声母 y w'),
  consonantSpec('py-13', '声母 y w', '第 13 课', ['y', 'w'], '认识这两个会帮韵母成音节的小帮手。', '下一节预告：b / d 区分'),
  consonantSpec('py-14', 'b / d 区分', '第 14 课', ['b', 'd'], '重点看开口方向和手势提示，别再混淆。', '下一节预告：p / q 区分'),
  consonantSpec('py-15', 'p / q 区分', '第 15 课', ['p', 'q'], '用送气和字形方向双重辨别。', '下一节预告：f / t 区分'),
  consonantSpec('py-16', 'f / t 区分', '第 16 课', ['f', 't'], '一个像小旗吹风，一个像伞柄站立。', '下一节预告：j q x 与 ü'),
  consonantSpec('py-17', 'j q x 与 ü 规则', '第 17 课', ['j', 'q', 'x', 'ü'], '记住“见了 j q x，两点要省略”的规则。', '下一节预告：两拼音节'),
  consonantSpec('py-18', '两拼音节基础', '第 18 课', ['b+a', 'm+o', 'd+e'], '把声母和韵母合成一个完整音节。', '下一节预告：三拼音节'),
  consonantSpec('py-19', '三拼音节基础', '第 19 课', ['g-u-a', 'h-u-o', 'x-u-an'], '学会把介母一起顺滑带过去。', '下一节预告：声母综合闯关'),
  consonantSpec('py-20', '声母综合闯关', '第 20 课', ['声母总复习'], '把前面学过的声母做一次综合运用和纠错。', '下一节预告：复韵母 ai ei ui'),
];

function finalSpec(id, title, badge, focus, previewLesson) {
  return {
    id,
    title,
    lessonType: '复韵母 / 鼻韵母',
    lessonBadge: badge,
    tagline: `${focus.join('、')} 这组韵母会在同一节里做滑动口型、拼读和辨音练习。`,
    focus,
    goals: [`会读 ${focus.join('、')}`, '能在词语里听出目标韵母', '能完成拼读和辨析'],
    practiceWords: focus.map((item) => `${item} 词卡`),
    practiceSentence: `把 ${focus.join('、')} 放进词语里，做到连贯不拆开。`,
    miniTask: `课后用 ${focus[0]} 或 ${focus[focus.length - 1]} 各说一个词。`,
    checkpoints: ['会读本课韵母', '知道口型如何滑动或收尾', '能完成一轮拼读闯关'],
    previewLesson,
    assetNotes: commonAssetPlan,
    introPrompt: `滑动手机上的音波轨道，把 ${focus.join('、')} 这组声音唤出来。`,
    introTvScene: `电视端出现漂浮的声音轨道，${focus.join('、')} 的字母卡依次亮起。`,
    introControllerScene: '手机出现可滑动的音波滑条。',
    introInteraction: '孩子滑动后，目标韵母按顺序进入舞台中央。',
    introFeedback: `旁白提示：“今天先把 ${focus.join('、')} 听熟。”`,
    coreSoundPrompt: '看老师的口型变化，感受从前一个元音滑向后一个元音或鼻音收尾。',
    coreSoundTvScene: '电视展示口型滑动动画和目标词语示例。',
    coreSoundControllerScene: '手机出现麦克风和口型轨迹线。',
    coreSoundInteraction: '孩子跟读时，电视上的轨迹线会跟着滑动。',
    coreSoundFeedback: '系统提示是否读得顺滑。',
    coreShapePrompt: '观察每个韵母的字母组合，记住它们是怎么拼在一起的。',
    coreShapeTvScene: '电视把目标韵母拆成元音组合或鼻尾结构。',
    coreShapeControllerScene: '手机探照灯依次照亮组成部分。',
    coreShapeInteraction: '孩子逐个观察结构并点亮。',
    coreShapeFeedback: '完成后合并成完整韵母。',
    gameOneTitle: '拼读滑梯',
    gameOnePrompt: '听音后选出正确韵母，让小车滑到终点。',
    gameOneTvScene: '电视上有多个带韵母标记的滑梯轨道。',
    gameOneControllerScene: '手机上是多个韵母按钮。',
    gameOneInteraction: '选对后小车会沿对应轨道冲下去。',
    gameOneFeedback: '答对点亮音节徽章。',
    gameTwoTitle: '韵母寻宝',
    gameTwoPrompt: '控制角色只去收集本课目标韵母。',
    gameTwoTvScene: '电视场景里散落着多种韵母宝石。',
    gameTwoControllerScene: '手机方向键或摇杆控制角色。',
    gameTwoInteraction: '孩子收集正确韵母宝石，避开干扰项。',
    gameTwoFeedback: '收尾回顾今天的目标韵母。',
    wrapPrompt: '跟着电视回顾口型和写法，再读一轮本课韵母。',
    wrapTvScene: '电视上依次展示韵母在四线三格中的书写与标调位置。',
    wrapControllerScene: '手机横屏显示描写板和复习卡。',
    wrapInteraction: '孩子选择其中一个韵母描写或点读。',
    wrapFeedback: `完成后播放“${previewLesson}”预告。`,
  };
}

const stageThreeLessons = [
  finalSpec('py-21', '复韵母 ai ei ui', '第 21 课', ['ai', 'ei', 'ui'], '下一节预告：复韵母 ao ou iu'),
  finalSpec('py-22', '复韵母 ao ou iu', '第 22 课', ['ao', 'ou', 'iu'], '下一节预告：复韵母 ie üe er'),
  finalSpec('py-23', '复韵母 ie üe er', '第 23 课', ['ie', 'üe', 'er'], '下一节预告：前鼻韵母'),
  finalSpec('py-24', '前鼻韵母 an en in un ün', '第 24 课', ['an', 'en', 'in', 'un', 'ün'], '下一节预告：后鼻韵母'),
  finalSpec('py-25', '后鼻韵母 ang eng ing ong', '第 25 课', ['ang', 'eng', 'ing', 'ong'], '下一节预告：复韵母闯关'),
  finalSpec('py-26', '复韵母拼读闯关', '第 26 课', ['ai', 'ao', 'ou', 'iu', 'ie'], '下一节预告：鼻韵母辨析'),
  finalSpec('py-27', '前后鼻音辨析', '第 27 课', ['an/ang', 'en/eng', 'in/ing'], '下一节预告：韵母综合应用'),
  finalSpec('py-28', '韵母综合应用', '第 28 课', ['复韵母', '鼻韵母'], '下一节预告：整体认读音节'),
];

function wholeReadSpec(id, title, badge, focus, previewLesson) {
  return {
    id,
    title,
    lessonType: '整体认读音节',
    lessonBadge: badge,
    tagline: '这些音节要整体记住，不拆拼，直接快速认读。',
    focus,
    goals: [`能整体认读 ${focus.join('、')}`, '知道它们不需要拆开拼', '能在词语里快速定位'],
    practiceWords: focus.map((item) => `${item} 词例`),
    practiceSentence: '看到整体认读音节时，要一眼认出，整块读出。',
    miniTask: `把 ${focus.slice(0, 3).join('、')} 连读三轮。`,
    checkpoints: ['知道是整体认读音节', '能整块读出', '能在词语里找到它们'],
    previewLesson,
    assetNotes: commonAssetPlan,
    introPrompt: `点亮整体认读魔法门，把 ${focus.join('、')} 一次性请出来。`,
    introTvScene: '电视端是一个会打开的魔法门，门后藏着目标音节卡。',
    introControllerScene: '手机出现发光门把手按钮。',
    introInteraction: '点亮后，目标音节卡整块飞出，不再拆开显示。',
    introFeedback: '旁白提示“这些要整体记住”。',
    coreSoundPrompt: '听老师整块读一遍，再跟着一口气读出来。',
    coreSoundTvScene: '电视展示整体认读音节和对应词语配图。',
    coreSoundControllerScene: '手机出现麦克风和整块认读进度条。',
    coreSoundInteraction: '孩子开口时，进度条按整块音节点亮。',
    coreSoundFeedback: '系统提示“这次没有拆开，读得更好了”。',
    coreShapePrompt: '把这些音节按类别放进记忆盒，形成组块记忆。',
    coreShapeTvScene: '电视把目标音节按卷舌组、平舌组、y 组分类陈列。',
    coreShapeControllerScene: '手机拖动分类卡片到对应盒子。',
    coreShapeInteraction: '孩子拖拽分类后，大屏同步归位。',
    coreShapeFeedback: '全部分类完成后出现整组总览。',
    gameOneTitle: '整块抢答',
    gameOnePrompt: '听到词语后，选出对应的整体认读音节。',
    gameOneTvScene: '电视有多个整块音节通道。',
    gameOneControllerScene: '手机是多个整块按钮。',
    gameOneInteraction: '选对后，角色冲进对应通道。',
    gameOneFeedback: '连续正确会点亮“整体记忆”奖章。',
    gameTwoTitle: '词语寻宝',
    gameTwoPrompt: '控制角色在词语森林里找到目标整体音节。',
    gameTwoTvScene: '词语卡片散落在森林中。',
    gameTwoControllerScene: '手机是方向键。',
    gameTwoInteraction: '孩子寻找包含目标整体音节的词卡。',
    gameTwoFeedback: '回顾本课音节和词语。',
    wrapPrompt: '跟着电视复读一遍，再快速认一遍卡片。',
    wrapTvScene: '电视展示本课整体认读音节总表和词例。',
    wrapControllerScene: '手机横屏出现复习闪卡。',
    wrapInteraction: '孩子快速滑动闪卡完成复习。',
    wrapFeedback: `收尾播放“${previewLesson}”预告。`,
  };
}

const stageFourLessons = [
  wholeReadSpec('py-29', 'zhi chi shi ri', '第 29 课', ['zhi', 'chi', 'shi', 'ri'], '下一节预告：zi ci si'),
  wholeReadSpec('py-30', 'zi ci si', '第 30 课', ['zi', 'ci', 'si'], '下一节预告：yi wu yu ye yue yuan'),
  wholeReadSpec('py-31', 'yi wu yu ye yue yuan', '第 31 课', ['yi', 'wu', 'yu', 'ye', 'yue', 'yuan'], '下一节预告：yin yun ying'),
  wholeReadSpec('py-32', 'yin yun ying 综合', '第 32 课', ['yin', 'yun', 'ying'], '下一节预告：句子拼读'),
];

function challengeSpec(id, title, badge, focus, previewLesson) {
  return {
    id,
    title,
    lessonType: '综合实战',
    lessonBadge: badge,
    tagline: '把前面学过的拼音真正用到句子、挑战和结课复习里。',
    focus,
    goals: ['能把拼音知识放进真实任务', '能更顺地拼读和理解', '为最后测评做准备'],
    practiceWords: focus,
    practiceSentence: '拼音不只是会读单个音，更要能拿来读词语和句子。',
    miniTask: '把今天最难的一处单独再练两遍。',
    checkpoints: ['能完成课堂挑战', '能说出自己的易错点', '能准备进入结课测评'],
    previewLesson,
    assetNotes: commonAssetPlan,
    introPrompt: '点亮挑战卷轴，进入综合任务。',
    introTvScene: '电视画面是会展开的任务卷轴，今天的挑战内容缓缓出现。',
    introControllerScene: '手机出现发光卷轴按钮。',
    introInteraction: '孩子点亮卷轴后，任务标题进入舞台中央。',
    introFeedback: '旁白提示“今天要把前面学过的内容都用起来”。',
    coreSoundPrompt: '先跟老师读，再自己完成挑战中的关键句。',
    coreSoundTvScene: '电视展示句子或挑战词条，并给出停顿与重音提示。',
    coreSoundControllerScene: '手机出现麦克风和任务进度条。',
    coreSoundInteraction: '孩子跟读或朗读时，进度条会逐句推进。',
    coreSoundFeedback: '系统给出“流畅”“再试一次”的提示。',
    coreShapePrompt: '把重点字词和结构找出来，帮助自己更稳地完成挑战。',
    coreShapeTvScene: '电视把关键音节、声调或易错点标成高亮。',
    coreShapeControllerScene: '手机可滑动放大重点位置。',
    coreShapeInteraction: '孩子逐一查看并完成记忆确认。',
    coreShapeFeedback: '关键点全部点亮后进入游戏。',
    gameOneTitle: '综合闯关',
    gameOnePrompt: '根据题目要求选对拼音、词语或句子。',
    gameOneTvScene: '电视端出现关卡门，每道门对应一项任务。',
    gameOneControllerScene: '手机展示题目按钮或选项卡。',
    gameOneInteraction: '孩子答对后打开对应关卡门。',
    gameOneFeedback: '每过一关就拿到一枚徽章。',
    gameTwoTitle: '复习冲刺',
    gameTwoPrompt: '把今天的重点内容做最后一次快速复习。',
    gameTwoTvScene: '电视端滚动出现复习卡片和倒计时。',
    gameTwoControllerScene: '手机上是快答按钮或滑动卡片。',
    gameTwoInteraction: '孩子在倒计时内完成快答。',
    gameTwoFeedback: '结束后给出本课复习结果。',
    wrapPrompt: '跟着电视做最后总结，并看看下一节要学什么。',
    wrapTvScene: '电视端展示本课总结海报、奖章和预告卡。',
    wrapControllerScene: '手机横屏显示总结卡和描写/确认区。',
    wrapInteraction: '孩子点击完成或跟写重点内容。',
    wrapFeedback: `收尾播放“${previewLesson}”预告。`,
  };
}

const stageFiveLessons = [
  challengeSpec('py-33', '句子拼读', '第 33 课', ['词语连读', '句子停顿', '拼读应用'], '下一节预告：绕口令挑战'),
  challengeSpec('py-34', '绕口令挑战', '第 34 课', ['节奏', '声母辨析', '快速反应'], '下一节预告：结课复习'),
  challengeSpec('py-35', '结课复习', '第 35 课', ['声母', '韵母', '整体认读', '易错点'], '下一节预告：结课测评'),
  challengeSpec('py-36', '结课测评', '第 36 课', ['综合测评', '学习总结', '毕业奖励'], '恭喜完成 36 节拼音课程'),
];

const curriculumStages = [
  createStageLesson(
    'stage-1-vowels',
    '第 1-6 课：单韵母',
    '围绕 a、o、e、i、u、ü 及四声调做沉浸式入门。',
    stageOneLessons,
  ),
  createStageLesson(
    'stage-2-initials',
    '第 7-20 课：声母',
    '声母学习重点加入易混淆辨析和基础拼读。',
    stageTwoLessons,
  ),
  createStageLesson(
    'stage-3-finals',
    '第 21-28 课：复韵母与鼻韵母',
    '先学复韵母，再通过前后鼻音做专项辨析。',
    stageThreeLessons,
  ),
  createStageLesson(
    'stage-4-whole-read',
    '第 29-32 课：整体认读音节',
    '把 16 个整体认读音节拆成 4 节课去记忆和应用。',
    stageFourLessons,
  ),
  createStageLesson(
    'stage-5-challenge',
    '第 33-36 课：综合实战与总结',
    '用句子、绕口令、复习和测评完成收尾。',
    stageFiveLessons,
  ),
];

function buildCurriculum() {
  let order = 1;

  return curriculumStages.map((stage, stageIndex) => {
    const lessons = stage.lessons.map((item, lessonIndex) => {
      let stepCursor = 1;
      const teachingFlow = item.teachingFlow.map((flowStage, flowStageIndex) => {
        const steps = flowStage.steps.map((step, stepIndex) => ({
          ...step,
          stageId: flowStage.id,
          stageTitle: flowStage.title,
          stageOrder: flowStageIndex + 1,
          stageStepIndex: stepIndex + 1,
          stepIndex: stepCursor++,
        }));

        return {
          ...flowStage,
          order: flowStageIndex + 1,
          stepCount: steps.length,
          steps,
        };
      });

      const steps = teachingFlow.flatMap((flowStage) => flowStage.steps);

      return {
        ...item,
        order: order++,
        stageId: stage.id,
        stageTitle: stage.title,
        stageIndex: stageIndex + 1,
        stageLessonIndex: lessonIndex + 1,
        teachingFlow,
        steps,
        totalStepCount: steps.length,
      };
    });

    return {
      ...stage,
      lessonCount: lessons.length,
      estimatedMinutes: lessons.reduce((total, item) => total + item.durationMinutes, 0),
      lessons,
    };
  });
}

const stages = buildCurriculum();
const lessons = stages.flatMap((stage) => stage.lessons);
const lessonMap = new Map(lessons.map((item) => [item.id, item]));

function getCurriculumStages() {
  return stages;
}

function getCurriculumLessons() {
  return lessons;
}

function getLessonById(lessonId) {
  return lessonMap.get(lessonId) || null;
}

module.exports = {
  getCurriculumLessons,
  getCurriculumStages,
  getLessonById,
};
